version: "3.8"

services:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    networks:
      - elastic
    volumes:
      - logstashdata:/usr/share/logstash/data
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
  debezium:
    image: quay.io/debezium/server:2.6
    container_name: debezium
    healthcheck:
      test: curl http://debezium:8080/q/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - elastic
      - h5traveloto
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    volumes:
      - ./debezium_conf:/debezium/conf:readonly

networks:
  h5traveloto:
    external: true

  elastic:
    driver: bridge
volumes:
  esdata:
    driver: local
  logstashdata:
    driver: local

